#include <stdio.h>

void get(int n)
{
    if (n < 1)
    {
        return;
    }
    get(n-1);
    get(n-3);
    printf("%d ", n);
}

int main()
{
    get(6);
}

/*
/*
================================================================================
                    RECURSION TREE NOTES
================================================================================

PROBLEM ANALYSIS
--------------------------------------------------------------------------------
Given the following recursive C function:

void get(int n) {
    if (n < 1) return;
    get(n - 1);
    get(n - 3);
    printf("%d", n);
}

Question: If get(6) is called in main(), how many times will the get() function 
be invoked (including the initial call) before returning to main()?


1. UNDERSTANDING THE CALL STRUCTURE
--------------------------------------------------------------------------------
When a function contains more than one recursive call, tracking it via a basic 
linear stack trace becomes highly complex. Instead, we model the execution 
using a "Recursion Tree".

* For any active node 'get(n)':
  - It triggers a left branch call to 'get(n - 1)'
  - It triggers a right branch call to 'get(n - 3)'
* Base Case: If n < 1, the function returns immediately. Even though it returns 
  instantly, this STILL counts as a function invocation.


2. COUNTING TOTAL INVOCATIONS USING FUNCTIONAL EQUATIONS
--------------------------------------------------------------------------------
Let T(n) represent the total number of function invocations generated by calling 
get(n). 

The general recurrence relation for the number of calls is:
T(n) = 1 + T(n - 1) + T(n - 3)

Where:
* 1 is the invocation of the current function call get(n) itself.
* T(n - 1) is the number of invocations from the first recursive call.
* T(n - 3) is the number of invocations from the second recursive call.

Base Cases (for n < 1):
* For any value of n less than 1, the function is invoked, hits the base case, 
  and returns. No further nested calls are made.
* Therefore: T(0) = 1, T(-1) = 1, T(-2) = 1, etc.


3. STEP-BY-STEP EVALUATION (BOTTOM-UP APPROACH)
--------------------------------------------------------------------------------
Let us calculate the value of T(n) starting from the smallest positive integer 
upwards to T(6):

* For n = 1:
  T(1) = 1 + T(0) + T(-2)
  T(1) = 1 + 1 + 1 = 3

* For n = 2:
  T(2) = 1 + T(1) + T(-1)
  T(2) = 1 + 3 + 1 = 5

* For n = 3:
  T(3) = 1 + T(2) + T(0)
  T(3) = 1 + 5 + 1 = 7

* For n = 4:
  T(4) = 1 + T(3) + T(1)
  T(4) = 1 + 7 + 3 = 11

* For n = 5:
  T(5) = 1 + T(4) + T(2)
  T(5) = 1 + 11 + 5 = 17

* For n = 6:
  T(6) = 1 + T(5) + T(3)
  T(6) = 1 + 17 + 7 = 25


4. CONCLUSION & CORRECT ANSWER
--------------------------------------------------------------------------------
The get() function will be invoked exactly 25 times during the execution of get(6).

Correct Answer: 25

================================================================================
*/